### PR TITLE
fix(metro-plugin-typescript): disable if unsupported Metro version

### LINKED ISSUE #1703: Cannot read properties of undefined (reading 'platform')
### What happened?

Hi, i have just integrated the rnx bundler into my app but when i run bundler using  `react-native rnx-start` command i get the following error :

`Cannot read properties of undefined (reading 'platform')`
`at Object.hook [as experimentalSerializerHook] (/Users/.../node_modules/@rnx-kit/cli/lib/metro-config.js:25:49)`

### Affected Package

@rnx-kit/cli

### Version

0.14.0

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1
    Memory: 169.45 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 28, 29, 30, 31, 32
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 32.1.0
      System Images: android-32 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.11 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

just integrating to an existing app

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tido64**
### Description

`@rnx-kit/metro-plugin-typescript` should be disabled if on Metro <0.66.

Resolves #1703.

### Test plan

```
cd packages/test-app
yarn build --dependencies
yarn bundle:ios
```

### CODE REVIEW

File: packages/metro-plugin-typescript/src/serializerHook.ts [hunk 1]
```diff
@@ -24,6 +40,12 @@ export function TypeScriptPlugin(
     return () => void 0;
   }
 
+  const unsupportedMetroVersion = checkMetroVersion(">=0.66.0");
```
Comment (kelset) [inline packages/metro-plugin-typescript/src/serializerHook.ts:43]: can we add a small reference to why it's >= .066 (ex link to 0.66 changelog at the entry that tells us that the feature is supported)

File: packages/tools-react-native/src/metro.ts [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+  const cliPath = resolveDependency("@react-native-community/cli", rnPath);
+  if (!cliPath) {
+    return undefined;
+  }
+
+  const cliMetroPath = resolveDependency(
+    "@react-native-community/cli-plugin-metro",
+    cliPath
+  );
+  return resolveDependency("metro", cliMetroPath || cliPath);
```
Comment (kelset) [inline packages/tools-react-native/src/metro.ts:33]: we're gonna have to keep an eye on this in the future since we know that they are thinking of decoupling metro and cli... but just writing it now as a headsup
