### PR TITLE
fix: use `esbuild` transform profile when `metro-serializer-esbuild` is used

### LINKED ISSUE #142: Metro: Also enable `disableImportExportTransform` when `experimentalImportSupport` is
When enabling `experimentalImportSupport` in `metro.config.js`:

```js
module.exports = {
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: true,
        inlineRequires: true,
      },
    }),
  },
};
```

`disableImportExportTransform` should also be enabled in `babel.config.js`:

```js
module.exports = {
  presets: [
    [
      "module:metro-react-native-babel-preset",
      { disableImportExportTransform: true },
    ],
  ],
};
```

When `babel.config.js` is missing, `disableImportExportTransform` is set to the value of `experimentalImportSupport` in [`metro-react-native-babel-transformer`](https://github.com/facebook/metro/blob/fa096594bcdeda8fe529aba94604016a1c3cbf93/packages/metro-react-native-babel-transformer/src/index.js#L93). Since we're recommending folks to use our preset, we need to find a way to keep both in sync somehow.

### PR DESCRIPTION
**Pull request by tido64**
### Description

Use `esbuild` transform profile when `metro-serializer-esbuild` is used.

Resolves #142.

### Test plan

```
cd packages/test-app
yarn build --dependencies
yarn bundle+esbuild --dev false --platform ios --reset-cache
```

| Before | After |
| :- | :- |
| 684314 | 585154 |

### CODE REVIEW

File: packages/metro-serializer-esbuild/src/index.ts [hunk 1]
```diff
@@ -123,6 +123,9 @@ export function MetroSerializer(
 ): SerializerConfigT["customSerializer"] {
   assertVersion(">=0.66.1");
 
+  // Signal to every plugin that we're using esbuild.
+  process.env[`RNX_METRO_SERIALIZER_ESBUILD_${process.pid}`] = "true";
```
Comment (afoxman) [inline packages/metro-serializer-esbuild/src/index.ts:127]: Why include the PID? It will only propagate to child processes. And since it's a signal to all of them, do you need the PID? I feel like I'm missing something.

**Review by afoxman — APPROVED** [review]

File: packages/metro-serializer-esbuild/src/index.ts (hunk 1 above)
Comment (tido64) [reply packages/metro-serializer-esbuild/src/index.ts:127]: It's for the case where you are running two bundlers at the same time. We can't guarantee that both are using this serializer.

Comment (tido64) [reply packages/metro-serializer-esbuild/src/index.ts:127]: Actually, I may have overthought this. The environment variables shouldn't be shared between two separate processes.
