### PR TITLE
fix(cli): add support for `@react-native-community/cli` 7.0.3

### LINKED ISSUE #1483: attachToServer is not a function. on empty project
### What happened?

I was trying to enable type safe bundling server in order to have type safe bundling, i followed the [guide](https://microsoft.github.io/rnx-kit/docs/guides/bundling) for bundling but it won't work, even on a blank project.

[Here](https://github.com/fbeccaceci/rnx-kit-issue-example) is a repository containing the blank project which is not working for me 

### Affected Package

@rnx-kit/cli

### Version

0.12.3

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 2.39 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.15 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.4, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.3/13E113 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

- Create a new project with `npx react-native init`
- Following the [bundling](https://microsoft.github.io/rnx-kit/docs/guides/bundling) guide on the documentation website
- run `npx react-native rnx-start`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tido64**
### Description

The return type of `createDevServerMiddleware()` changed in https://github.com/react-native-community/cli/pull/1560.

Resolves #1483.

### Test plan

```
git clone https://github.com/fbeccaceci/rnx-kit-issue-example.git
cd rnx-kit-issue-example
yarn
npx react-native rnx-start
```

### CODE REVIEW

File: packages/cli/src/start.ts [hunk 1]
```diff
@@ -217,12 +257,12 @@ export async function rnxStart(
 
           case "d":
             terminal.log(chalk.green("Opening developer menu..."));
-            messageSocket.broadcast("devMenu", undefined);
+            messageSocketEndpoint.broadcast("devMenu", undefined);
```
Comment (tido64) [inline packages/cli/src/start.ts:260]: @afoxman: FYI, it looks like this command no longer works. It doesn't work with `npx react-native start` either. Reload still works however.

Comment (afoxman) [reply packages/cli/src/start.ts:260]: Filed #1485 to track it. I wonder if the command name or args changed.

**Review by afoxman — APPROVED** [review]
