### PR TITLE
fix loadConfig parameters

### LINKED ISSUE #3212: [Windows] @rnx-kit/preset broken with new versions of RNW
### What happened?

RNW uses @rnx-kit/preset in our CI. When trying to cut the 0.75 branch, we got errors when RNW upgraded to any react-native version above [0.75.0-nightly-20240618-5df5ed1a8](https://www.npmjs.com/package/react-native/v/0.75.0-nightly-20240618-5df5ed1a8) and the 0.75 release candidates. 

image

### Affected Package

@rnx-kit/jest-preset

### Version

0.1.16

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [X] Windows

### System Information

```true
npm WARN config This command does not support workspaces.
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.22631
  CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Memory: 33.55 GB / 63.85 GB
Binaries:
  Node:
    version: 18.18.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.5
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 8.18.0
    path: ~\AppData\Roaming\npm\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.17763.0
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: AI-213.7172.25.2113.9014738
  Visual Studio:
    - 16.11.34931.43 (Visual Studio Enterprise 2019)
    - 17.10.35004.147 (Visual Studio Enterprise 2022)
Languages:
  Java:
    version: 11.0.16.1
    path: C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to Reproduce

Try to use @rnx-kit/jest-preset with an RNW app above [0.75.0-nightly-20240618-5df5ed1a8](https://www.npmjs.com/package/react-native/v/0.75.0-nightly-20240618-5df5ed1a8) or look at the RNW 0.75.0-preview-branch https://github.com/microsoft/react-native-windows/tree/preview-0.75-test

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TatianaKapos**
### Description

@react-native-community/cli-config recently changed the input of [LoadConfig](https://github.com/react-native-community/cli/pull/2379), this let's @rnx-kit/preset handle the new input.

Resolves #3212.

### Test plan

Tested locally on the RNW repository

### CODE REVIEW

File: packages/jest-preset/src/index.js [hunk 1]
```diff
@@ -96,7 +96,7 @@ function getTargetPlatform(defaultPlatform, searchPaths) {
     return getReactNativePlatformPath();
   }
 
-  /** @type {() => CLIConfig} */
+  /** @type {(config?: object) => CLIConfig} */
```
Comment (acoates-ms) [inline packages/jest-preset/src/index.js:99]: config?: {
  projectRoot?: string;
  selectedPlatform?: string;
}

File: packages/jest-preset/src/index.js [hunk 2]
```diff
@@ -96,7 +96,7 @@ function getTargetPlatform(defaultPlatform, searchPaths) {
     return getReactNativePlatformPath();
   }
 
-  /** @type {() => CLIConfig} */
+  /** @type {(config?:  {projectRoot?: string;selectedPlatform?: string;}) => CLIConfig} */
```
Comment (tido64) [inline packages/jest-preset/src/index.js:99]: Nit:
```suggestion
  /** @type {(config?: {projectRoot?: string; selectedPlatform?: string; }) => CLIConfig} */
```

**Review by tido64 — APPROVED** [review]

File: .changeset/rich-months-speak.md [hunk 3]
```diff
@@ -0,0 +1,5 @@
+---
+"@rnx-kit/jest-preset": minor
+---
+
+fixes jest-preset calling new loadConfig from @react-native-community/cli-config
```
Comment (tido64) [inline .changeset/rich-months-speak.md:5]:
```suggestion
"@rnx-kit/jest-preset": patch
---

Support new `loadConfig` signature from `@react-native-community/cli-config`
```

**Comment by tido64** [comment]
Thanks for submitting a fix. I'm oof atm so I'm doing everything on my phone but I'll try to get this published later today.
