### PR TITLE
CLI updates

### LINKED ISSUE #521: CI: fail bundling when type-checking fails
### Description

In CI loops, fail bundling when type-checking fails. This would have caught a bug in the type-checking code which only happened on windows (which I don't run during development).

### Your environment

- Affected package:
- Version:
- Tested platforms:
  - [ ] Android
  - [ ] iOS
  - [ ] macOS
  - [ ] Windows
- System information:
  ```
  # Run `npx react-native info` and paste the output here
  ```

### PR DESCRIPTION
**Pull request by afoxman**
### Description

The CLI's TypeScript support is currently limited to validating source files in one package -- the app being bundled/served. If the app depends on other packages in the same monorepo, sources from those packages won't be type-checked.

This PR expands the reach of the CLI, allowing it to type-check sources from all packages in the monorepo. External packages (anything under node_modules) are ignored.

The CLI buckets source files by their parent package, and uses the package's tsconfig when checking those files.

This PR also adds type-checking options, which vary between bundling and serving. Bundling, for example, will throw when validation fails, causing the entire bundling run to fail. Serving, will only print type errors to the console, and continue without interruption.

Resolves #521.

### Test plan

Existing CI tests pass. There isn't much test coverage in this area of the CLI. That issue is tracked under #375.

### CODE REVIEW

File: packages/cli/src/typescript/project-cache.ts [hunk 1]
```diff
@@ -0,0 +1,152 @@
...
+    }
+    return projects[root][platform]!;
+  }
+
+  function clearPlatform(platform: AllPlatforms): void {
+    Object.values(projects).forEach((projectsByPlatform) => {
+      if (projectsByPlatform[platform]) {
+        projectsByPlatform[platform]!.dispose();
+        delete projectsByPlatform[platform];
+      }
```
Comment (tido64) [inline packages/cli/src/typescript/project-cache.ts:144]: Nit: Can we store a temp variable to avoid the nonnull assertion?
```suggestion
      const project = projectsByPlatform[platform]
      if (project) {
        project.dispose();
        delete projectsByPlatform[platform];
      }
```

File: packages/cli/src/start.ts [hunk 2]
```diff
@@ -120,35 +119,17 @@ export async function rnxStart(
...
+    print: (message: string): void => {
+      terminal.log(message);
+    },
+  };
   customizeMetroConfig(
     metroConfig,
     serverConfig.detectCyclicDependencies,
     serverConfig.detectDuplicateDependencies,
-    tsprojectInfo,
+    serverConfig.typescriptValidation ? typescriptValidationOptions : false,
```
Comment (tido64) [inline packages/cli/src/start.ts:132]: Isn't it possible to pass options here? Won't this ignore them?

File: packages/cli/src/typescript/project-cache.ts (hunk 1 above)
Comment (afoxman) [reply packages/cli/src/typescript/project-cache.ts]: Fixed

File: packages/cli/src/start.ts (hunk 2 above)
Comment (afoxman) [reply packages/cli/src/start.ts:132]: Defaults -- print messages to the console, don't throw on a type-validation error.

Comment (tido64) [reply packages/cli/src/start.ts:132]: Aren't we getting `serverConfig` from the config (`package.json`)? If the user sets an object there, we would lose it here.

Comment (tido64) [reply packages/cli/src/start.ts:132]: Never mind. It looks like we only allow boolean values for the `typescriptValidation` option: https://github.com/microsoft/rnx-kit/blob/12fa18216536fa4cbe81aed918326079b6969fe5/packages/config/src/bundleConfig.ts#L33-L38

**Review by tido64 — APPROVED** [review]
