### PR TITLE
fix(metro-config): wrong module resolved due to ignoring symlinks

### LINKED ISSUE #585: metro-resolver-symlinks throws error because of excludeExtraCopiesOf
### What happened?

Made a brand new react native project with the react native typescript template. Installed dependencies with pnpm and added some rnx-kit stuff.

Added the symlink resolver to metro.config.js.

First error I was getting was like 
`MetroSymlinksResolver is not a function.`
This was from the example in the readme which I copy pasted. I had to use `const MetroSymlinksResolver = require('@rnx-kit/metro-resolver-symlinks').default` instead.

After that I started getting `react could not be found.`

I followed the exception down to around here:
```
 * @param {string} name
 * @param {string=} projectRoot
 * @returns {string | undefined}
 */
function resolveModule(name, projectRoot) {
  const { findPackageDependencyDir } = require("@rnx-kit/tools-node/package");
  return findPackageDependencyDir(
    { name },
    { startDir: projectRoot, allowSymlinks: false }
  );
}
```
where allowSymlinks is hardcoded as false in @rnx-kit/metro-config.

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.2

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
Error: Command failed: wmic os get Caption
'wmic' is not recognized as an internal or external command,
operable program or batch file.

Well, something is messed up here.
```

### Steps to Reproduce

[Repro repo](https://github.com/icesuicune/rnxSymlinkErrorRepro)
pnpm install -g
cd MyApp
pnpm install
pnpx rnx-kit --config ./metro.config.js

The repo is basically the react native generated template, with bits taken from the /test app package in this project.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tido64**
### Description

In a pnpm-managed repository, we cannot ignore symlinks. This change will allow symlinks, and resolve them to a real path.

Resolves #585.

### Test plan

Check out the repro in #585:

```
git clone https://github.com/icesuicune/rnxSymlinkErrorRepro.git
cd rnxSymlinkErrorRepro/MyApp
pnpm install
pnpm react-native bundle --entry-file index.js --platform ios --dev true --bundle-output dist/main.ios.jsbundle --assets-dest dist
```

### CODE REVIEW

File: packages/metro-config/src/index.js [hunk 1]
```diff
@@ -62,10 +62,11 @@ function defaultWatchFolders(projectRoot) {
  */
 function resolveModule(name, projectRoot) {
   const { findPackageDependencyDir } = require("@rnx-kit/tools-node/package");
-  return findPackageDependencyDir(
+  const result = findPackageDependencyDir(
     { name },
-    { startDir: projectRoot, allowSymlinks: false }
```
Comment (afoxman) [inline packages/metro-config/src/index.js:67]: Function comment should be updated to match the new behavior.

**Review by afoxman — APPROVED** [review]
